sudo: required
dist: xenial
language: cpp
os: linux
compiler: g++

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - timsc
    packages:
      - cmake-data
      - cmake
      - g++-6
      - libopencv-core3.4
      - libopencv-imgproc3.4
      - libopencv-highgui3.4
      - libopencv-dev

before_install:
 - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install opencv && brew install qt5 && brew link --force qt5; fi
 # additional headerfiles
 - sudo apt-get -y install libxxf86vm-dev libxi-dev libudev-dev libxcursor-dev
 - sudo apt-get -y install -f qtbase5-dev qt5-default qttools5-dev-tools libqt5opengl5-dev
 - sudo apt-get -y install libfreeimage-dev

script:
 - qmake -recursive PREFIX=/app
 - make
 - sudo make install

after_success:
 - find /app
 - curl --upload-file /app/bin/imageplay https://transfer.sh/imageplay
 - sudo bash -ex appimage.sh
 
branches:
  only:
    - master
